GET http://localhost:3003/api/blogs/

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhbCIsImlkIjoiNjY1MGUzNjU1NTdiNjI2OGRlMmZjMzk4IiwiaWF0IjoxNzE2NjMxMTUxfQ.Cxwu9Q71_hkqZuR2ScGBgBOiZJ9zW0DEG2mh097BFI0

{
    "title": "Demo4",
    "author": "Abdellatif",
    "url": "toto.com",
    "likes": "15"
}

###
GET http://localhost:3003/api/users/

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "sal",
    "name": "nki",
    "password": "123qwe"
}

###
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "sal",
    "password": "123qwe"
} 